CREATE TABLE IF NOT EXISTS `base_account` (
  `account_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `account` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `account_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `register_ip` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT '1',
  `domain` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  `must_change_password` int DEFAULT '0',
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_action` (
  `action_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `menu_id` bigint DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `action_desc` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT '1',
  `is_persist` int DEFAULT '0',
  `service_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`action_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_api` (
  `api_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `service_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_category` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `api_desc` text COLLATE utf8mb4_unicode_ci,
  `status` int DEFAULT '1',
  `is_persist` tinyint(1) DEFAULT '0',
  `is_auth` tinyint(1) DEFAULT '1',
  `is_open` int DEFAULT '0',
  `request_method` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `class_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `method_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `access_log` tinyint(1) DEFAULT NULL,
  `business_scope` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_api_key` (
  `key_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `developer_id` bigint NOT NULL,
  `biz_app_id` bigint DEFAULT NULL,
  `api_key` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `secret_key` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `public_key` longtext COLLATE utf8mb4_unicode_ci,
  `private_key` longtext COLLATE utf8mb4_unicode_ci,
  `key_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `key_desc` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scope_modules` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expire_time` timestamp NULL DEFAULT NULL,
  `status` int DEFAULT '1',
  `revoke_time` timestamp NULL DEFAULT NULL,
  `last_used_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`key_id`),
  UNIQUE KEY `idx_base_api_key_api_key` (`api_key`),
  KEY `idx_base_api_key_developer_id` (`developer_id`),
  KEY `idx_base_api_key_biz_app_id` (`biz_app_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_app` (
  `app_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `secret_key` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'pc',
  `app_icon` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_icons` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_name_en` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_os` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `developer_id` bigint DEFAULT NULL,
  `app_desc` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT '1',
  `is_persist` int DEFAULT '0',
  `public_key` longtext COLLATE utf8mb4_unicode_ci,
  `private_key` longtext COLLATE utf8mb4_unicode_ci,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  `org_id` bigint DEFAULT NULL,
  PRIMARY KEY (`app_id`),
  UNIQUE KEY `api_key_index` (`api_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_area` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  `area_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `area_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `area_type` int DEFAULT NULL,
  `full_pin_yin` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `simple_pin_yin` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `center_location` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_base_area_area_code` (`area_code`),
  KEY `idx_base_area_parent_code` (`parent_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='行政区域';
CREATE TABLE IF NOT EXISTS `base_authority` (
  `authority_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authority` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resource_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `menu_id` bigint DEFAULT NULL,
  `api_id` bigint DEFAULT NULL,
  `action_id` bigint DEFAULT NULL,
  `status` int DEFAULT '1',
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`authority_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_authority_action` (
  `id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authority_id` bigint NOT NULL,
  `action_id` bigint NOT NULL,
  `expire_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_authority_apikey` (
  `id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `key_id` bigint NOT NULL,
  `authority_id` bigint NOT NULL,
  `expire_time` timestamp NULL DEFAULT NULL,
  `auth_status` int DEFAULT '1',
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `idx_base_authority_apikey_key_id` (`key_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_authority_app` (
  `id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authority_id` bigint NOT NULL,
  `expire_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_authority_role` (
  `id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authority_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  `expire_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_authority_user` (
  `id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authority_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `expire_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_developer` (
  `user_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company_id` bigint DEFAULT NULL,
  `nick_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobile` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_desc` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT '1',
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_dic` (
  `id` bigint NOT NULL,
  `name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `css_class` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `list_class` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `service_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `idx_base_dic_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_menu` (
  `menu_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `menu_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `menu_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icon` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scheme` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `menu_desc` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT '1',
  `is_persist` tinyint(1) DEFAULT '0',
  `service_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hidden` int DEFAULT '1',
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_org` (
  `id` bigint NOT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `org_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `org_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `manager_id` bigint DEFAULT NULL,
  `source_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `group_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `leader_id` bigint DEFAULT NULL,
  `org_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `number_of_accounts` int DEFAULT NULL,
  `org_address` text COLLATE utf8mb4_unicode_ci,
  `status` int DEFAULT '1',
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `idx_base_org_parent_id` (`parent_id`),
  KEY `idx_base_org_group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_role` (
  `role_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role_desc` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT '1',
  `is_persist` int DEFAULT '0',
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_role_user` (
  `id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_user` (
  `user_id` bigint NOT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company_id` bigint DEFAULT NULL,
  `department_id` bigint DEFAULT NULL,
  `nick_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `real_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobile` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sex` int DEFAULT NULL,
  `user_desc` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT '1',
  `close_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_user_org` (
  `id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `org_id` bigint NOT NULL,
  `expire_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `idx_base_user_org_user_org` (`user_id`,`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `custom_forms` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `menu_ids` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_or_table` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_source` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  `detail` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `idx_custom_forms_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='自定义表单主表';
CREATE TABLE IF NOT EXISTS `custom_forms_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `form_id` bigint NOT NULL,
  `field_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `field_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `component_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_required` bit(1) DEFAULT NULL,
  `is_filter` bit(1) DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  `format` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `decimal_type` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `decimal_value` int DEFAULT NULL,
  `choice_type` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `choice_value` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_type` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_show` bit(1) DEFAULT NULL,
  `field_belong` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `value_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `label_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `children_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='自定义表单字段明细';
CREATE TABLE IF NOT EXISTS `extend_form_definition` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `form_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `form_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fields_json` longtext COLLATE utf8mb4_unicode_ci,
  `version` int DEFAULT '1',
  `custom_form_id` bigint DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_extend_form_tenant_code` (`tenant_id`,`form_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='扩展字段表单定义（按租户隔离，发布后写入 Redis）';
CREATE TABLE IF NOT EXISTS `gateway_ip_limit` (
  `policy_id` bigint NOT NULL,
  `policy_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `policy_type` int DEFAULT NULL,
  `ip_address` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`policy_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网关 IP 访问策略';
CREATE TABLE IF NOT EXISTS `gateway_ip_limit_api` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `policy_id` bigint NOT NULL,
  `api_id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gateway_ip_limit_api` (`policy_id`,`api_id`),
  KEY `idx_gateway_ip_limit_api_api` (`api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网关 IP 策略与接口关联';
CREATE TABLE IF NOT EXISTS `gateway_rate_limit` (
  `policy_id` bigint NOT NULL,
  `policy_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `policy_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `limit_quota` bigint DEFAULT NULL,
  `interval_unit` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`policy_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网关限流策略';
CREATE TABLE IF NOT EXISTS `gateway_rate_limit_api` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `policy_id` bigint NOT NULL,
  `api_id` bigint NOT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gateway_rate_limit_api` (`policy_id`,`api_id`),
  KEY `idx_gateway_rate_limit_api_api` (`api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网关限流策略与接口关联';
CREATE TABLE IF NOT EXISTS `gateway_route` (
  `route_id` bigint NOT NULL,
  `route_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `path` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `service_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `strip_prefix` int DEFAULT NULL,
  `retryable` int DEFAULT NULL,
  `status` int DEFAULT NULL,
  `is_persist` int DEFAULT NULL,
  `route_desc` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `extend_data` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`route_id`),
  UNIQUE KEY `uk_gateway_route_name` (`route_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网关动态路由';
CREATE TABLE IF NOT EXISTS `open_api_document` (
  `doc_id` bigint NOT NULL,
  `service_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_url` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `spec_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `raw_spec` longtext COLLATE utf8mb4_unicode_ci,
  `source_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sync_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sync_message` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sync_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`doc_id`),
  KEY `idx_open_api_document_service_id` (`service_id`),
  KEY `idx_open_api_document_source_hash` (`source_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `open_api_operation` (
  `operation_id` bigint NOT NULL,
  `doc_id` bigint DEFAULT NULL,
  `api_id` bigint DEFAULT NULL,
  `service_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `path` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `request_method` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tags` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `summary` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci,
  `operation_key` varchar(768) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parameters_json` longtext COLLATE utf8mb4_unicode_ci,
  `request_body_json` longtext COLLATE utf8mb4_unicode_ci,
  `responses_json` longtext COLLATE utf8mb4_unicode_ci,
  `schemas_json` longtext COLLATE utf8mb4_unicode_ci,
  `security_json` longtext COLLATE utf8mb4_unicode_ci,
  `examples_json` longtext COLLATE utf8mb4_unicode_ci,
  `raw_operation_json` longtext COLLATE utf8mb4_unicode_ci,
  `deprecated` int DEFAULT '0',
  `is_open` int DEFAULT '0',
  `is_auth` int DEFAULT '1',
  `status` int DEFAULT '1',
  `sync_state` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_seen_time` timestamp NULL DEFAULT NULL,
  `last_seen_time` timestamp NULL DEFAULT NULL,
  `removed_time` timestamp NULL DEFAULT NULL,
  `change_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sync_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`operation_id`),
  UNIQUE KEY `idx_open_api_operation_operation_key` (`operation_key`),
  KEY `idx_open_api_operation_service_path_method` (`service_id`,`path`,`request_method`),
  KEY `idx_open_api_operation_api_id` (`api_id`),
  KEY `idx_open_api_operation_sync_state` (`sync_state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `published_api_doc` (
  `published_id` bigint NOT NULL,
  `doc_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `published_spec` longtext COLLATE utf8mb4_unicode_ci,
  `published_summary` longtext COLLATE utf8mb4_unicode_ci,
  `source_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `publisher_user_id` bigint DEFAULT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `status` int DEFAULT '1',
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `id` bigint DEFAULT NULL,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`published_id`),
  UNIQUE KEY `idx_published_api_doc_doc_key` (`doc_key`),
  KEY `idx_published_api_doc_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_account_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  `user_id` bigint DEFAULT NULL,
  `account` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `login_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `login_time` datetime DEFAULT NULL,
  `ip` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int DEFAULT NULL,
  `message` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_app_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  `app_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `org_id` bigint DEFAULT NULL,
  `config_content` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_base_app_config_key_org` (`app_key`,`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_release_info` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  `release_time` datetime DEFAULT NULL,
  `package_time` datetime DEFAULT NULL,
  `release_content` text COLLATE utf8mb4_unicode_ci,
  `user_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version_number` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `package_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `base_user_certification` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  `user_id` bigint NOT NULL,
  `id_card` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expiration_date` datetime DEFAULT NULL,
  `effective_date` datetime DEFAULT NULL,
  `certification_type` int DEFAULT NULL,
  `status` int DEFAULT NULL,
  `face_image` text COLLATE utf8mb4_unicode_ci,
  `fingerprint` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `data_source_management` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_id` bigint DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `leaf_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `extend_data` text COLLATE utf8mb4_unicode_ci,
  `data_source_code` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `data_source_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `data_source_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `customize_content` text COLLATE utf8mb4_unicode_ci,
  `url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_method` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_header` text COLLATE utf8mb4_unicode_ci,
  `request_body` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `data_source_code` (`data_source_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `jbm_system_init_marker` (
  `marker_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `initialized_at` timestamp NOT NULL,
  PRIMARY KEY (`marker_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
