version: "1.0"
build:
  project_type: python
  use_project_dockerfile: true
  dockerfile_name: Dockerfile.doc-connection
  platforms: [linux/amd64, linux/arm64]
image:
  name: jbm-cluster-platform-doc
  prefix: registry.cn-shanghai.aliyuncs.com/okc
  tag: py-7.3.23-doc-connection-20260920
  push: true
push_mode: multi
services:
  - name: jbm-cluster-platform-doc
    image_name: jbm-cluster-platform-doc
