from __future__ import annotations

from typing import Any, Mapping, Protocol


class GovernanceRepository(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def health(self) -> dict[str, Any]: ...

    async def list_users(
        self, page: int, size: int, keyword: str | None, filters: Mapping[str, Any]
    ) -> tuple[list[dict[str, Any]], int]: ...

    async def get_user(self, user_id: int) -> dict[str, Any] | None: ...

    async def user_roles(self, user_id: int) -> list[dict[str, Any]]: ...

    async def user_orgs(self, user_id: int) -> list[dict[str, Any]]: ...

    async def user_accounts(self, user_id: int) -> list[dict[str, Any]]: ...

    async def user_authorities(self, user_id: int, is_admin: bool) -> list[dict[str, Any]]: ...

    async def user_menus(
        self, user_id: int, app_id: int | None, is_admin: bool
    ) -> list[dict[str, Any]]: ...

    async def list_orgs(self, keyword: str | None = None) -> list[dict[str, Any]]: ...

    async def list_dicts(self, parent_id: int | None = None) -> list[dict[str, Any]]: ...

    async def list_apps(
        self, page: int, size: int, filters: Mapping[str, Any]
    ) -> tuple[list[dict[str, Any]], int]: ...

    async def list_roles(
        self, page: int, size: int, filters: Mapping[str, Any]
    ) -> tuple[list[dict[str, Any]], int]: ...

    async def list_routes(
        self, page: int, size: int, filters: Mapping[str, Any]
    ) -> tuple[list[dict[str, Any]], int]: ...

    async def dashboard_counts(self) -> dict[str, int]: ...
