<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jbm</groupId>
        <artifactId>jbm-framework-autoconfigure</artifactId>
        <version>7.2.21-SNAPSHOT</version>
    </parent>

    <artifactId>jbm-framework-autoconfigure-drools</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.github.hongwen1993</groupId>
            <artifactId>fast-drools-spring-boot-starter</artifactId>
            <version>8.0.9</version>
        </dependency>
        <!--Drools-->
    </dependencies>
</project>