spring:
  application:
    name: jbm-cluster-platform-auth
  cloud:
    nacos:
      discovery:
        server-addr: 10.100.10.62:8848
        namespace: jbm7
        group: DEFAULT_GROUP
      config:
        enabled: true
        server-addr: 10.100.10.62:8848
        namespace: jbm7
        group: DEFAULT_GROUP
        shared-dataids: common.properties,db.properties,redis.properties

server:
  host: 0.0.0.0
  port: 5555

jbm:
  auth:
    jwt:
      issuer: http://jbm-cluster-platform-auth:5555
