--liquibase formatted sql
--changeset jbm:job-v1-tables splitStatements:true

CREATE TABLE IF NOT EXISTS sys_job (
    job_id            BIGINT       NOT NULL PRIMARY KEY,
    id                BIGINT,
    code              VARCHAR(64),
    app_id            BIGINT,
    parent_id         BIGINT,
    level             INT,
    leaf_path         VARCHAR(512),
    job_name          VARCHAR(128) NOT NULL,
    job_group         VARCHAR(128) NOT NULL,
    invoke_target     VARCHAR(1024),
    method_type       VARCHAR(16),
    cron_expression   VARCHAR(255),
    misfire_policy    INT,
    concurrent        BOOLEAN,
    record_log        BOOLEAN,
    status            INT,
    create_by         VARCHAR(128),
    update_by         VARCHAR(128),
    description       VARCHAR(512),
    extend_data       LONGTEXT,
    create_time       TIMESTAMP,
    update_time       TIMESTAMP,
    UNIQUE KEY uk_sys_job_name_group (job_name, job_group),
    KEY idx_sys_job_status (status),
    KEY idx_sys_job_group (job_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_job_log (
    job_log_id        BIGINT       NOT NULL PRIMARY KEY,
    id                BIGINT,
    code              VARCHAR(64),
    app_id            BIGINT,
    parent_id         BIGINT,
    level             INT,
    leaf_path         VARCHAR(512),
    job_name          VARCHAR(128),
    run_time          BIGINT,
    job_group         VARCHAR(128),
    invoke_target     VARCHAR(1024),
    job_message       LONGTEXT,
    status            VARCHAR(32),
    exception_info    LONGTEXT,
    start_time        TIMESTAMP,
    stop_time         TIMESTAMP,
    extend_data       LONGTEXT,
    create_time       TIMESTAMP,
    update_time       TIMESTAMP,
    KEY idx_sys_job_log_name_group (job_name, job_group),
    KEY idx_sys_job_log_status (status),
    KEY idx_sys_job_log_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rule_definition (
    id                BIGINT       NOT NULL PRIMARY KEY,
    code              VARCHAR(64),
    app_id            BIGINT,
    parent_id         BIGINT,
    level             INT,
    leaf_path         VARCHAR(512),
    rule_code         VARCHAR(128),
    rule_name         VARCHAR(128),
    rule_group        VARCHAR(128),
    rule_desc         VARCHAR(512),
    rule_status       BOOLEAN,
    rule_content      LONGTEXT,
    drools_content    LONGTEXT,
    version           VARCHAR(64),
    extend_data       LONGTEXT,
    create_time       TIMESTAMP,
    update_time       TIMESTAMP,
    KEY idx_rule_definition_code (rule_code),
    KEY idx_rule_definition_group (rule_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rule_operation_log (
    id                  BIGINT       NOT NULL PRIMARY KEY,
    code                VARCHAR(64),
    app_id              BIGINT,
    parent_id           BIGINT,
    level               INT,
    leaf_path           VARCHAR(512),
    rule_id             BIGINT,
    rule_code           VARCHAR(128),
    rule_name           VARCHAR(128),
    rule_group          VARCHAR(128),
    rule_desc           VARCHAR(512),
    rule_status         BOOLEAN,
    rule_content        LONGTEXT,
    version             VARCHAR(64),
    operation_user      VARCHAR(128),
    operation_user_name VARCHAR(128),
    operation_time      TIMESTAMP,
    extend_data         LONGTEXT,
    create_time         TIMESTAMP,
    update_time         TIMESTAMP,
    KEY idx_rule_operation_log_rule_id (rule_id),
    KEY idx_rule_operation_log_rule_code (rule_code),
    KEY idx_rule_operation_log_operation_time (operation_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workflow_definition (
    id                BIGINT       NOT NULL PRIMARY KEY,
    code              VARCHAR(64),
    app_id            BIGINT,
    parent_id         BIGINT,
    level             INT,
    leaf_path         VARCHAR(512),
    workflow_code     VARCHAR(128),
    workflow_name     VARCHAR(128),
    workflow_group    VARCHAR(128),
    workflow_desc     VARCHAR(512),
    workflow_status   BOOLEAN,
    json_content      LONGTEXT,
    bpmn_content      LONGTEXT,
    version           VARCHAR(64),
    extend_data       LONGTEXT,
    create_time       TIMESTAMP,
    update_time       TIMESTAMP,
    KEY idx_workflow_definition_code (workflow_code),
    KEY idx_workflow_definition_group (workflow_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dynamic_class (
    id                BIGINT       NOT NULL PRIMARY KEY,
    code              VARCHAR(64),
    app_id            BIGINT,
    parent_id         BIGINT,
    level             INT,
    leaf_path         VARCHAR(512),
    class_name        VARCHAR(128) NOT NULL,
    package_name      VARCHAR(255),
    description       VARCHAR(512),
    extend_data       LONGTEXT,
    create_time       TIMESTAMP,
    update_time       TIMESTAMP,
    KEY idx_dynamic_class_name (class_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dynamic_field (
    id                BIGINT       NOT NULL PRIMARY KEY,
    code              VARCHAR(64),
    app_id            BIGINT,
    parent_id         BIGINT,
    level             INT,
    leaf_path         VARCHAR(512),
    class_id          BIGINT       NOT NULL,
    field_name        VARCHAR(128) NOT NULL,
    field_type        VARCHAR(128) NOT NULL,
    field_label       VARCHAR(255),
    extend_data       LONGTEXT,
    create_time       TIMESTAMP,
    update_time       TIMESTAMP,
    KEY idx_dynamic_field_class_id (class_id),
    KEY idx_dynamic_field_name (field_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS process_instance (
    id                 VARCHAR(64)  NOT NULL PRIMARY KEY,
    code               VARCHAR(64),
    app_id             BIGINT,
    parent_id          BIGINT,
    level              INT,
    leaf_path          VARCHAR(512),
    rule_definition_id BIGINT,
    rule_name          VARCHAR(128),
    rule_content       LONGTEXT,
    status             VARCHAR(32),
    input_params       LONGTEXT,
    output_params      LONGTEXT,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    extend_data        LONGTEXT,
    create_time        TIMESTAMP,
    update_time        TIMESTAMP,
    KEY idx_process_instance_rule_definition_id (rule_definition_id),
    KEY idx_process_instance_status (status),
    KEY idx_process_instance_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS node_execution (
    id                  VARCHAR(64)  NOT NULL PRIMARY KEY,
    code                VARCHAR(64),
    app_id              BIGINT,
    parent_id           BIGINT,
    level               INT,
    leaf_path           VARCHAR(512),
    process_instance_id VARCHAR(64),
    node_id             VARCHAR(128),
    node_type           VARCHAR(64),
    status              VARCHAR(32),
    input_data          LONGTEXT,
    output_data         LONGTEXT,
    error_message       LONGTEXT,
    started_at          TIMESTAMP,
    completed_at        TIMESTAMP,
    extend_data         LONGTEXT,
    create_time         TIMESTAMP,
    update_time         TIMESTAMP,
    KEY idx_node_execution_process_instance_id (process_instance_id),
    KEY idx_node_execution_node_id (node_id),
    KEY idx_node_execution_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS process_trigger (
    id                  VARCHAR(64)  NOT NULL PRIMARY KEY,
    code                VARCHAR(64),
    app_id              BIGINT,
    parent_id           BIGINT,
    level               INT,
    leaf_path           VARCHAR(512),
    process_instance_id VARCHAR(64),
    node_id             VARCHAR(128),
    trigger_type        VARCHAR(64),
    trigger_key         VARCHAR(255),
    status              VARCHAR(32),
    trigger_data        LONGTEXT,
    created_at          TIMESTAMP,
    triggered_at        TIMESTAMP,
    extend_data         LONGTEXT,
    create_time         TIMESTAMP,
    update_time         TIMESTAMP,
    KEY idx_process_trigger_process_instance_id (process_instance_id),
    KEY idx_process_trigger_node_id (node_id),
    KEY idx_process_trigger_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
