#emqx.api.url=http://emqx:8081
#emqx.api.username=admin
#emqx.api.password=public
emqx.sync.enabled=true
emqx.sync.cron=0 0/5 * * * *
# HTTP hooks (EMQX callback endpoints)
#emqx.hooks.enabled=true
#emqx.hooks.path=/emqx/hooks