server:
  port: 9999

spring:
  application:
    name: jbm-cluster-platform-doc
  cloud:
    nacos:
      discovery:
        server-addr: 10.100.10.62:8848
        namespace: jbm7
        group: DEFAULT_GROUP
      config:
        server-addr: 10.100.10.62:8848
        namespace: jbm7
        group: DEFAULT_GROUP
        shared-dataids: common.properties,db.properties,redis.properties,rabbitmq.properties,doc.properties
