spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.100.10.62:8848
        namespace: jbm7
        group: DEFAULT_GROUP
      config:
        enabled: false

integrations:
  redis:
    enabled: true
    url: redis://127.0.0.1:6379/0
